name: publish to pypi
on: push
  branches:
        - main
jobs:
  build-n-publish:
    name: publish to pypi
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master
      -name: set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      -name: install pypa/build
        run: >-
          python -m 
          pip install build
          --user
      -name: build binary wheel and source tar ball
        run: >-
          python -m 
          build 
          --sdist
          --wheel
          --outdir dist/
      -name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
          skip_existing: True